local colorscheme = require("mini.colorscheme")

local colors = {
    bright = {
        orange  = colorscheme.convert(20,  0.5, 1.0),
        yellow  = colorscheme.convert(40,  0.5, 1.0),
        green   = colorscheme.convert(80,  0.5, 1.0),
        cyan    = colorscheme.convert(180, 0.5, 1.0),
        blue    = colorscheme.convert(210, 0.5, 1.0),
        purple  = colorscheme.convert(260, 0.4, 1.0),
        magenta = colorscheme.convert(330, 0.5, 1.0),
        red     = colorscheme.convert(350, 0.5, 1.0),
    },
    dark = {
        orange  = colorscheme.convert(20,  0.5, 0.1),
        yellow  = colorscheme.convert(40,  0.5, 0.1),
        green   = colorscheme.convert(80,  0.5, 0.1),
        cyan    = colorscheme.convert(180, 0.5, 0.1),
        blue    = colorscheme.convert(210, 0.5, 0.1),
        purple  = colorscheme.convert(260, 0.4, 0.1),
        magenta = colorscheme.convert(330, 0.5, 0.1),
        red     = colorscheme.convert(350, 0.5, 0.1),
    },
    gray = {
        [ 1  ] = colorscheme.convert(210, 0.4, 0.07),
        [ 2  ] = colorscheme.convert(210, 0.4, 0.1),
        [ 3  ] = colorscheme.convert(210, 0.5, 0.2),
        [ 4  ] = colorscheme.convert(210, 0.5, 0.3),
        [ 5  ] = colorscheme.convert(210, 0.3, 0.4),
        [ 6  ] = colorscheme.convert(210, 0.3, 0.5),
        [ 7  ] = colorscheme.convert(210, 0.3, 0.6),
        [ 8  ] = colorscheme.convert(210, 0.3, 0.7),
        [ 9  ] = colorscheme.convert(210, 0.2, 0.8),
        [ 10 ] = colorscheme.convert(210, 0.2, 1.0),
    },
    black = colorscheme.convert(0, 0.0, 0.0),
    white = colorscheme.convert(0, 0.0, 1.0),

    none = NONE,
}

local color = {
    [ "ColorColumn"     ] = { colors.gray[2],       colors.none          },
    [ "Comment"         ] = { colors.none,          colors.gray[6]       },
    [ "Conditional"     ] = { colors.none,          colors.bright.red    },
    [ "Constant"        ] = { colors.none,          colors.bright.orange },
    [ "CurSearch"       ] = { colors.bright.orange, colors.black         },
    [ "CursorLine"      ] = { colors.gray[2],       colors.none          },
    [ "CursorLineNr"    ] = { colors.gray[3],       colors.gray[7]       },
    [ "CursorLineSign"  ] = { colors.gray[3],       colors.none          },
    [ "Delimiter"       ] = { colors.none,          colors.gray[8]       },
    [ "DiagnosticError" ] = { colors.dark.red,      colors.bright.red    },
    [ "DiagnosticHint"  ] = { colors.dark.green,    colors.bright.green  },
    [ "DiagnosticInfo"  ] = { colors.dark.blue,     colors.bright.blue   },
    [ "DiagnosticWarn"  ] = { colors.dark.orange,   colors.bright.orange },
    [ "Directory"       ] = { colors.none,          colors.bright.blue   },
    [ "EndOfBuffer"     ] = { colors.none,          colors.gray[3]       },
    [ "Function"        ] = { colors.none,          colors.bright.blue   },
    [ "Identifier"      ] = { colors.none,          colors.gray[10]      },
    [ "IncSearch"       ] = { colors.bright.orange, colors.black         },
    [ "Include"         ] = { colors.none,          colors.bright.red    },
    [ "IndentLine"      ] = { colors.none,          colors.gray[4]       },
    [ "Keyword"         ] = { colors.none,          colors.bright.red    },
    [ "LineNr"          ] = { colors.gray[1],       colors.gray[5]       },
    [ "Macro"           ] = { colors.none,          colors.bright.red    },
    [ "Normal"          ] = { colors.none,          colors.none          },
    [ "NormalFloat"     ] = { colors.gray[2],       colors.none          },
    [ "Number"          ] = { colors.none,          colors.bright.orange },
    [ "Operator"        ] = { colors.none,          colors.bright.red    },
    [ "Pmenu"           ] = { colors.gray[1],       colors.gray[9]       },
    [ "PmenuExtra"      ] = { colors.none,          colors.bright.purple },
    [ "PmenuExtraSel"   ] = { colors.gray[3],       colors.bright.purple },
    [ "PmenuKind"       ] = { colors.none,          colors.bright.red    },
    [ "PmenuKindSel"    ] = { colors.gray[3],       colors.bright.red    },
    [ "PmenuMatch"      ] = { colors.none,          colors.bright.blue   },
    [ "PmenuSel"        ] = { colors.gray[3],       colors.gray[10]      },
    [ "PreCondit"       ] = { colors.none,          colors.bright.red    },
    [ "PreProc"         ] = { colors.none,          colors.bright.red    },
    [ "Repeat"          ] = { colors.none,          colors.bright.red    },
    [ "Search"          ] = { colors.bright.yellow, colors.black         },
    [ "SignColumn"      ] = { colors.gray[2],       colors.none          },
    [ "Special"         ] = { colors.none,          colors.gray[9]       },
    [ "Statement"       ] = { colors.none,          colors.bright.red    },
    [ "String"          ] = { colors.none,          colors.bright.green  },
    [ "Structure"       ] = { colors.none,          colors.bright.purple },
    [ "Type"            ] = { colors.none,          colors.bright.purple },
    [ "Visual"          ] = { colors.gray[3],       colors.none          },
    [ "WinSeparator"    ] = { colors.gray[3],       colors.gray[3]       },

    [ "LspSignatureActiveParameter" ] = { colors.gray[4], colors.none },

    [ "StatusLine"             ] = { colors.gray[1],       colors.none    },
    [ "StatusLineNC"           ] = { colors.gray[1],       colors.none    },
    [ "StatusLineAlignment"    ] = { colors.gray[2],       colors.none    },
    [ "StatusLineAlignmentNC"  ] = { colors.gray[1],       colors.none    },
    [ "StatusLineBranch"       ] = { colors.gray[4],       colors.gray[9] },
    [ "StatusLineBranchNC"     ] = { colors.gray[3],       colors.gray[8] },
    [ "StatusLineDiagnostic"   ] = { colors.gray[4],       colors.gray[9] },
    [ "StatusLineDiagnosticNC" ] = { colors.gray[3],       colors.gray[8] },
    [ "StatusLineFileName"     ] = { colors.gray[3],       colors.gray[8] },
    [ "StatusLineFileNameNC"   ] = { colors.gray[2],       colors.gray[7] },
    [ "StatusLineFileType"     ] = { colors.gray[3],       colors.gray[8] },
    [ "StatusLineFileTypeNC"   ] = { colors.gray[2],       colors.gray[7] },
    [ "StatusLineModeCommand"  ] = { colors.bright.red,    colors.black   },
    [ "StatusLineModeInsert"   ] = { colors.bright.green,  colors.black   },
    [ "StatusLineModeNC"       ] = { colors.gray[4],       colors.gray[9] },
    [ "StatusLineModeNormal"   ] = { colors.bright.blue,   colors.black   },
    [ "StatusLineModeReplace"  ] = { colors.bright.purple, colors.black   },
    [ "StatusLineModeVisual"   ] = { colors.bright.orange, colors.black   },
    [ "StatusLinePosition"     ] = { colors.bright.purple, colors.black   },
    [ "StatusLinePositionNC"   ] = { colors.gray[4],       colors.gray[9] },
}

local link = {
    [ "@comment"                   ] = "Comment",
    [ "@constant"                  ] = "Constant",
    [ "@function"                  ] = "Function",
    [ "@keyword"                   ] = "Keyword",
    [ "@lsp.type.class"            ] = "Structure",
    [ "@lsp.type.function"         ] = "Function",
    [ "@lsp.type.macro"            ] = "Macro",
    [ "@lsp.type.operator"         ] = "Operator",
    [ "@lsp.type.property"         ] = "Identifier",
    [ "@lsp.type.type"             ] = "Type",
    [ "@module.builtin"            ] = "Type",
    [ "@number"                    ] = "Number",
    [ "@operator"                  ] = "Operator",
    [ "@property"                  ] = "Identifier",
    [ "@punctuation"               ] = "Delimiter",
    [ "@string"                    ] = "String",
    [ "@type"                      ] = "Type",
    [ "@type.builtin"              ] = "Type",
    [ "DiagnosticUnnecessary"      ] = "Comment",
    [ "DiagnosticVirtualTextError" ] = "DiagnosticError",
    [ "DiagnosticVirtualTextHint"  ] = "DiagnosticHint",
    [ "DiagnosticVirtualTextInfo"  ] = "DiagnosticInfo",
    [ "DiagnosticVirtualTextWarn"  ] = "DiagnosticWarn",
    [ "LineNrAbove"                ] = "LineNr",
    [ "LineNrBelow"                ] = "LineNr",
}

colorscheme.execute(color, link)
